fixed package.json 9

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,18 +21,17 @@ jobs:
                   node-version: '22'
                   registry-url: 'https://registry.npmjs.org/'
                   scope: '@icemobile'
+                  always-auth: true
+                  token: ${{ secrets.NPM_TOKEN }}
 
             - name: Start ssh-agent
               uses: webfactory/ssh-agent@v0.5.4
               with:
                   ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-            - name: Authenticate to npm (for install)
+            - name: Debug npm auth
               run: |
-                  echo "@icemobile:registry=https://registry.npmjs.org/" >> ~/.npmrc
-                  echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
-              env:
-                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+                  npm whoami || echo "Failed auth"
 
             - name: Install dependencies
               run: npm ci
